# postgres/values.yaml

helm:
  values: |
    image:
      tag: 15.5.0-debian-12-r0

    auth:
      postgresPassword: StrongPass123
      username: appuser
      password: AppPass123
      database: appdb
auth:
  postgresPassword: "dba"
  username: appuser
  password: "dba"
  database: appdb

primary:
  persistence:
    enabled: true
    size: 5Gi

  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m

service:
  type: ClusterIP
